const products = [
  // ===== TOOLS =====

  {
    name: "Screw Driver",
    category: "tools",
    description: "Flat & Phillips head",
    sizes: ['3"', '4"', '5"', '6"', '8"'],
    alt: "Screw driver image",
  },
  {
    name: "Measuring Tape",
    category: "tools",
    description: "Steel measuring tape",
    sizes: ["3m", "5m", "8m", "10m", "20m", "30m"],
    alt: "Measuring tape image",
  },
  {
    name: "Drill Bit (Makita)",
    category: "tools",
    description: "Masonry drill bit",
    sizes: ["3mm", "4mm", "5mm", "6mm", "8mm", "10mm", "12mm", "14mm"],
    alt: "Drill bit image",
  },
  {
    name: "Drill Machine",
    category: "tools",
    description: "Corded electric drill",
    sizes: ["500W", "650W", "750W", "850W", "1100W"],
    alt: "Drill machine image",
  },
  {
    name: "Angle Grinder",
    category: "tools",
    description: "Heavy duty angle grinder",
    sizes: ["750W", "1400W", "2000W"],
    alt: "Angle grinder image",
  },
  {
    name: "Sledge Hammer",
    category: "tools",
    description: "Heavy duty sledge hammer",
    sizes: ["2lb", "3lb", "4lb", "6lb", "8lb", "10lb", "12lb"],
    alt: "Sledge hammer image",
  },
  {
    name: "Hand Saw",
    category: "tools",
    description: "Wood hand saw",
    sizes: ['14"', '16"', '18"', '20"'],
    alt: "Hand saw image",
  },
  {
    name: "Spanner (Combination)",
    category: "tools",
    description: "Combination spanner",
    sizes: ["8mm", "10mm", "12mm", "13mm", "14mm", "18mm", "19mm", "20mm"],
    alt: "Combination spanner image",
  },
  {
    name: "Spirit Level",
    category: "tools",
    description: "Aluminium spirit level",
    sizes: ["Mini", "30cm", "40cm", "60cm", "80cm", "100cm", "120cm", "200cm"],
    alt: "Spirit level image",
  },
  {
    name: "Cutting Disc",
    category: "tools",
    description: "Metal cutting disc",
    sizes: ['4"', '4.5"', '7"', '9"'],
    alt: "Cutting disc image",
  },
  {
    name: "Trowel",
    category: "tools",
    description: "Wooden handle trowel",
    sizes: ['6"', '7"', '8"'],
    alt: "Trowel image",
  },
  {
    name: "Pipe Wrench",
    category: "tools",
    description: "Heavy duty pipe wrench",
    sizes: ['8"', '10"', '12"', '14"', '18"', '24"'],
    alt: "Pipe wrench image",
  },
  {
    name: "Claw Hammer",
    category: "tools",
    description: "Sturdy claw hammer",
    sizes: ["Small", "Big"],
    alt: "Claw hammer image",
  },
  {
    name: "Bench Vice",
    category: "tools",
    description: "Heavy duty bench vice",
    sizes: ['4"', '5"', '6"', '8"'],
    alt: "Bench vice image",
  },
  {
    name: "F-Clamp",
    category: "tools",
    description: "Steel F-clamp",
    sizes: ["50x150mm", "50x250mm", "80x300mm", "120x500mm"],
    alt: "F-clamp image",
  },
  //curated list
  {
    name: "Air Blower",
    category: "tools",
    description: "400W/620W",
    sizes: ["400W"],
    alt: "Air Blower image",
  },
  {
    name: "Angle Grinder",
    category: "tools",
    description: "Ingco/Bosch",
    sizes: ["750W", "2000W"],
    alt: "Angle Grinder image",
  },
  {
    name: "Belt Sander",
    category: "tools",
    description: "Sanding machine-Tolsen/Bosch",
    sizes: ["750W", "810W"],
    alt: "Belt sander Image",
  },
  {
    name: "Finishing Sander",
    category: "tools",
    description: "Sanding Machine",
    sizes: ["320W", "350W"],
    alt: "Finishing Sander image",
  },
  {
    name: "Brush Cutter",
    category: "tools",
    description: "Petrol bush clearing Machine",
    sizes: ["2 stroke", "4 stroke-4 blade", "4-stroke-8 blade", "backpack"],
    alt: "brushCutter image",
  },
  {
    name: "Hand Lawn Mower",
    category: "tools",
    description: "Manual Push lawn mower",
    sizes: ["16 inch", "18 inch", "20 inch"],
    alt: "Hand lawn mower",
  },

  {
    name: "Drill Machine",
    category: "tools",
    description: "Corded Drill machine",
    sizes: ["680W", "750W", "850W", "900W", "1100W"],
    alt: "Drill machine image",
  },
  {
    name: " Cordless Drill Machine",
    category: "tools",
    description: "Battery powered drill machine",
    sizes: ["12V", "18V", "20V"],
    alt: "Drill machine cordless image",
  },

  {
    name: " Jig Saw Machine",
    category: "tools",
    description: "Electric jigsaw machine",
    sizes: ["400W", "570W", "650W"],
    alt: "Jigsaw Machine image",
  },
  {
    name: " Hot Air Gun",
    category: "tools",
    description: "Electric heat Gun",
    sizes: ["2000W"],
    alt: "Hot Air Gun Image",
  },
  {
    name: " Hot Glue Gun",
    category: "tools",
    description: "Electric glue gun",
    sizes: ["100W"],
    alt: "Hot glue Gun Image",
  },
  {
    name: " Spray Gun",
    category: "tools",
    description: "Electric spray gun",
    sizes: ["450W"],
    alt: "spray gun image",
  },
  {
    name: " Staple Gun",
    category: "tools",
    description: "4-14MM H/D",
    sizes: [],
    alt: "staple gun image",
  },
  {
    name: "Welding Machine",
    category: "tools",
    description: "Electric spray gun",
    sizes: ["180A", "200A"],
    alt: "spray gun image",
  },
  {
    name: " Optical level",
    category: "tools",
    description: "Complete Bosch Optical level",
    sizes: [],
    alt: "optical level Image",
  },

  // ===== BUILDING MATERIALS =====
  {
    name: "Square Tube",
    category: "building",
    description: "40x40x2mm steel",
    sizes: ["20X20MM", "30X30MM", "40 X 40MM", "50 X 50MM"],
    alt: "Square tube image",
  },
  {
    name: "Steel Bar",
    category: "building",
    description: "Deformed bars",
    sizes: ["D-8", "D-10", "D-12", "D-16"],
    alt: "Steel bar image",
  },
  {
    name: "Flat Bar",
    category: "building",
    description: "Steel bar",
    sizes: ["25MM", "30MM", "40MM", "50MM"],
    alt: "Flat bar image",
  },
  {
    name: "Round bar",
    category: "building",
    description: " Rounded steel bars",
    sizes: ["R-6", "R-10", "R-12", "R-16"],
    alt: "Flat bar image",
  },
  {
    name: "Bolt & Nuts",
    category: "building",
    description: "Assorted",
    sizes: ["1/4 Inch", "5/16 Inch", "3/8 Inch", "1/2 Inch"],
    alt: "Bolt and nuts image",
  },
  {
    name: "Wall Plug",
    category: "building",
    description: "plastic wall plugs",
    sizes: ["6mm", "8mm", "10mm", "12mm"],
    alt: "Wall plug image",
  },
  {
    name: "Manhole Cover",
    category: "building",
    description: "Fibre",
    sizes: [
      "12 x 12 Inch",
      "15 x 15 Inch",
      "18 X 18 Inch",
      "18 x 24 inch",
      "24 x 24 Inch",
    ],
    alt: "Manhole cover image",
  },
  {
    name: "Roofing Sheet",
    category: "building",
    description: "30 Gauge",
    sizes: ["2MTR", "2.5MTR", "3MTR"],
    alt: "Roofing sheet image",
  },
  {
    name: "Brass Screws",
    category: "building",
    description: "Brass flat head screws",
    sizes: ["25MM", "30MM", "40MM", "50MM", "60MM", "75MM", "100MM"],
    alt: "Gypsum screws image",
  },
  {
    name: "Gypsum Screws",
    category: "building",
    description: "Black philip head screws",
    sizes: ["25MM", "30MM", "40MM", "50MM", "60MM", "75MM", "100MM"],
    alt: "Gypsum screws image",
  },
  {
    name: "MDF Screws",
    category: "building",
    description: "Zinc Coated philip head screws",
    sizes: ["25MM", "30MM", "40MM", "50MM", "60MM", "75MM", "100MM"],
    alt: "mdf screw image screws image",
  },
  {
    name: "DPC (Damp Proof Course)",
    category: "building",
    description: "1m x 7m roll",
    alt: "DPC roll image",
  },
  {
    name: "Grout",
    category: "building",
    description: "tile grout-grey,white and cream",
    sizes: ["1kg", "3kg"],
    alt: "Tile grout image",
  },
  {
    name: "Weld Mesh",
    category: "building",
    description: "8 X 4ft ",
    sizes: ["2.5MM", "3MM", "4MM"],
    alt: "Weld mesh image",
  },
  {
    name: "Chainlink (Coated)",
    category: "building",
    description: "Green plastic coated chainlink",
    sizes: ["4FT", "5FT", "6FT", "7FT"],
    alt: "Coated chainlink image",
  },
  {
    name: "Chainlink (Galvanised)",
    category: "building",
    description: "Galvanised chainlink",
    sizes: ["4FT", "5FT", "6FT", "7FT"],
    alt: "Galvanised chainlink image",
  },
  {
    name: "Plywood",
    category: "building",
    description: "8 x 4ft plywood",
    sizes: ["3MM", "6MM", "9MM", "12MM"],
    alt: "Plywood  image",
  },
  {
    name: "Marine board",
    category: "building",
    description: "8 x 4ft black shutter board",
    sizes: ["18MM"],
    alt: "Marine board  image",
  },
  {
    name: "Block Board",
    category: "building",
    description: "8 x 4ft wooden board",
    sizes: ["18MM"],
    alt: "Block board image",
  },
  {
    name: "Rawl Bolt",
    category: "building",
    description: "Expanding bolts for concrete",
    sizes: ["M6", "M8", "M10", "M12"],
    alt: "Rawl bolt image",
  },
  {
    name: "Rawl Hook",
    category: "building",
    description: "Expanding hook for concrete",
    sizes: ["M6", "M8", "M10", "M12"],
    alt: "Rawl hook image",
  },
  {
    name: "Skim coat",
    category: "building",
    description: " Premium Int/Ext Wall filler",
    sizes: ["1KG", "2.5KG", "25KG"],
    alt: "Skim coat image",
  },

  // ===== PLUMBING =====
  {
    name: "Shower Mixer",
    category: "plumbing",
    description: "Hot & cold mixer, chrome",
    alt: "Shower mixer image",
  },
  {
    name: "Waste Bend",
    category: "plumbing",
    description: "1.25 inch",
    alt: "Waste bend image",
  },
  {
    name: "Shower Head",
    category: "plumbing",
    description: "8 inch rain shower",
    alt: "Shower head image",
  },
  {
    name: "Basin Mixer",
    category: "plumbing",
    description: "Single lever, chrome",
    alt: "Basin mixer image",
  },
  {
    name: "PPR Male Adapter",
    category: "plumbing",
    description: "32mm - 40mm",
    alt: "PPR male adapter image",
  },
  {
    name: "Sink Mixer",
    category: "plumbing",
    description: "Single lever kitchen mixer",
    alt: "Sink mixer image",
  },
  {
    name: "Pillar Tap",
    category: "plumbing",
    description: "Chrome, single",
    alt: "Pillar tap image",
  },
  {
    name: "PPR Pipe",
    category: "plumbing",
    description: "25mm PN20",
    alt: "PPR pipe image",
  },
  {
    name: "Water Heater",
    category: "plumbing",
    description: "15L Atlantic electric",
    alt: "Water heater image",
  },
  {
    name: "PPR Female Elbow",
    category: "plumbing",
    description: "25mm",
    alt: "PPR female elbow image",
  },
  {
    name: "PVC Tee",
    category: "plumbing",
    description: "3/4 inch",
    alt: "PVC tee image",
  },
  {
    name: "Water Pump",
    category: "plumbing",
    description: "Honda 5HP",
    alt: "Water pump image",
  },
  {
    name: "Kitchen Sink",
    category: "plumbing",
    description: "Double bowl, single drainer",
    alt: "Kitchen sink image",
  },
  {
    name: "Water Tank",
    category: "plumbing",
    description: "1000L",
    alt: "Water tank image",
  },
  {
    name: "Gate Valve",
    category: "plumbing",
    description: "1/2 inch brass",
    alt: "Gate valve image",
  },

  // ===== ELECTRICAL =====
  {
    name: "Flood Light (LED)",
    category: "electrical",
    description: "70W outdoor floodlight",
    alt: "LED flood light image",
  },
  {
    name: "Consumer Unit",
    category: "electrical",
    description: "6-way distribution board",
    alt: "Consumer unit image",
  },
  {
    name: "LED Bulb",
    category: "electrical",
    description: "5W, E27 / B22 fitting",
    alt: "LED bulb image",
  },
  {
    name: "Cable Clip",
    category: "electrical",
    description: "6mm round",
    alt: "Cable clip image",
  },
  {
    name: "Cable Ties (Black)",
    category: "electrical",
    description: "2.5 x 100mm, pack",
    alt: "Black cable ties image",
  },
  {
    name: "Capacitor",
    category: "electrical",
    description: "2uF - 10uF motor capacitor",
    alt: "Capacitor image",
  },
  {
    name: "Tube Light (LED)",
    category: "electrical",
    description: "4ft LED tube",
    alt: "LED tube light image",
  },
  {
    name: "Lamp Holder",
    category: "electrical",
    description: "Straight, ceiling type",
    alt: "Lamp holder image",
  },
  {
    name: "Extension Cord",
    category: "electrical",
    description: "4-way with surge protection",
    alt: "Extension cord image",
  },
  {
    name: "Ceiling Fan",
    category: "electrical",
    description: "Standard household fan",
    alt: "Ceiling fan image",
  },
  {
    name: "Bulkhead Light (LED)",
    category: "electrical",
    description: "Oval, weatherproof",
    alt: "LED bulkhead light image",
  },
  {
    name: "Strip Light",
    category: "electrical",
    description: "10W LED strip",
    alt: "Strip light image",
  },
  {
    name: "Trunking",
    category: "electrical",
    description: "25x16mm cable trunking",
    alt: "Trunking image",
  },
  {
    name: "Switch (Lisse)",
    category: "electrical",
    description: "1-2 gang wall switch",
    alt: "Wall switch image",
  },
  {
    name: "Down Light (LED)",
    category: "electrical",
    description: "6W recessed downlight",
    alt: "LED down light image",
  },

  // ===== SANITARY WARE =====
  {
    name: "Toilet Seat Cover",
    category: "sanitary-ware",
    description: "Standard fit",
    alt: "Toilet seat cover image",
  },
  {
    name: "Hand Wash Basin",
    category: "sanitary-ware",
    description: "14x11 inch corner basin",
    alt: "Hand wash basin image",
  },
  {
    name: "Asian Toilet",
    category: "sanitary-ware",
    description: "Ordinary squat toilet",
    alt: "Asian toilet image",
  },
  {
    name: "Bidet Mixer",
    category: "sanitary-ware",
    description: "Chrome bidet spray mixer",
    alt: "Bidet mixer image",
  },
  {
    name: "Center Waste",
    category: "sanitary-ware",
    description: "1.25 inch basin waste",
    alt: "Center waste image",
  },
  {
    name: "Shower Arm",
    category: "sanitary-ware",
    description: "Short, chrome",
    alt: "Shower arm image",
  },
  {
    name: "Telephone Shower (Flexible)",
    category: "sanitary-ware",
    description: "PVC hose, white",
    alt: "Flexible telephone shower image",
  },
  {
    name: "WC Connector",
    category: "sanitary-ware",
    description: "4 inch, blue",
    alt: "WC connector image",
  },
  {
    name: "Cistern Ball",
    category: "sanitary-ware",
    description: "Float valve for toilet cistern",
    alt: "Cistern ball image",
  },
  {
    name: "Flush Handle (Metal)",
    category: "sanitary-ware",
    description: "Lever type",
    alt: "Metal flush handle image",
  },
  {
    name: "Basin Stopper",
    category: "sanitary-ware",
    description: "Heavy duty",
    alt: "Basin stopper image",
  },
  {
    name: "Soap Dish",
    category: "sanitary-ware",
    description: "Stainless steel",
    alt: "Soap dish image",
  },
  {
    name: "Mirror Light (LED)",
    category: "sanitary-ware",
    description: "4W bathroom mirror light",
    alt: "LED mirror light image",
  },
  {
    name: "Arabic Shower",
    category: "sanitary-ware",
    description: "PVC hand shower",
    alt: "Arabic shower image",
  },
  {
    name: "Toilet Paper Holder",
    category: "sanitary-ware",
    description: "Chrome, wall mount",
    alt: "Toilet paper holder image",
  },

  // ===== HARDWARE GENERAL =====
  {
    name: "Cylinder Lock",
    category: "hardware-general",
    description: "Standard door cylinder",
    alt: "Cylinder lock image",
  },
  {
    name: "Brass Hinges",
    category: "hardware-general",
    description: "3x3 inch, pair",
    alt: "Brass hinges image",
  },
  {
    name: "Drawer Handle",
    category: "hardware-general",
    description: "Small metal pull handle",
    alt: "Drawer handle image",
  },
  {
    name: "Padlock (Triangular)",
    category: "hardware-general",
    description: "40mm, chrome plated",
    alt: "Triangular padlock image",
  },
  {
    name: "Nylon Rope",
    category: "hardware-general",
    description: "8mm, sold per metre",
    alt: "Nylon rope image",
  },
  {
    name: "Mortice Lock",
    category: "hardware-general",
    description: "2-lever door lock",
    alt: "Mortice lock image",
  },
  {
    name: "Hasp & Staple",
    category: "hardware-general",
    description: "4 inch, aluminium",
    alt: "Hasp and staple image",
  },
  {
    name: "Castor Wheel",
    category: "hardware-general",
    description: "1.5 inch swivel wheel",
    alt: "Castor wheel image",
  },
  {
    name: "Garden Shear",
    category: "hardware-general",
    description: "Heavy duty pruning shear",
    alt: "Garden shear image",
  },
  {
    name: "Lawn Mower",
    category: "hardware-general",
    description: "123cc, 16 inch cut",
    alt: "Lawn mower image",
  },
  {
    name: "Screw Hook",
    category: "hardware-general",
    description: "Assorted sizes",
    alt: "Screw hook image",
  },
  {
    name: "Curtain Rod",
    category: "hardware-general",
    description: "7ft, wooden",
    alt: "Curtain rod image",
  },
  {
    name: "Glass Cutter",
    category: "hardware-general",
    description: "Standard hand tool",
    alt: "Glass cutter image",
  },
  {
    name: "Life Jacket",
    category: "hardware-general",
    description: "Orange, adult size",
    alt: "Life jacket image",
  },
  {
    name: "Pool Net",
    category: "hardware-general",
    description: "Deep leaf net for pools",
    alt: "Pool net image",
  },

  // ===== PAINT - CROWN =====
  {
    name: "Covermatt",
    category: "paint-crown",
    type: "interior",
    description: "Budget interior matt emulsion",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown covermatt paint image",
  },
  {
    name: "Luxury",
    category: "paint-crown",
    type: "interior",
    description: "Premium interior emulsion",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown luxury paint image",
  },
  {
    name: "Vinyl Silk",
    category: "paint-crown",
    type: "interior",
    description: "Silk finish washable emulsion",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown vinyl silk paint image",
  },
  {
    name: "Permaplast",
    category: "paint-crown",
    type: "exterior",
    description: "Textured exterior finish",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown permaplast image",
  },
  {
    name: "Ultraguard Silicone",
    category: "paint-crown",
    type: "exterior",
    description: "Silicone exterior weather guard paint",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown silicone ultraguard image",
  },
  {
    name: "Super Gloss",
    category: "paint-crown",
    type: "exterior",
    description: " Premium Oil Based Paint ",
    sizes: ["1L", "4L"],
    alt: "Supergloss image",
  },

  {
    name: "Undercoat Int/Ext",
    category: "paint-crown",
    type: "exterior",
    description: "water-based undercoat",
    sizes: ["1L", "4L, 20L"],
    alt: "Undercoat int/ext image",
  },

  {
    name: "Woodseal Clear",
    category: "paint-crown",
    type: "wood",
    description: "Clear wood sealer",
    sizes: ["1L", "4L"],
    alt: "Crown woodseal clear image",
  },
  {
    name: "Matt Varnish clear",
    category: "paint-crown",
    type: "wood",
    description: "matt clear varnish",
    sizes: ["1L", "4L"],
    alt: "Matt varnish",
  },
  {
    name: "Sanding Sealer",
    category: "paint-crown",
    type: "wood",
    description: "Matt sealer for wood",
    sizes: ["1L", "4L"],
    alt: "Sanding sealer image",
  },
  {
    name: "Wood Primer",
    category: "paint-crown",
    type: "wood",
    description: "Wood primer",
    sizes: ["1L", "4L"],
    alt: "Crown wood primer image",
  },
  {
    name: "Chlorinated Rubber Paint",
    category: "paint-crown",
    type: "specialized",
    description: "Tough Chemical Resistant Paint ",
    sizes: ["1L", "4L"],
    alt: "Chlo-rubber paint image",
  },

  {
    name: "Road line paint",
    category: "paint-crown",
    type: "specialized",
    description: "Road marking paint",
    sizes: ["1L", "4L"],
    alt: "Road marking paint image",
  },
  {
    name: "Fungicidal wash",
    category: "paint-crown",
    type: "specialized",
    description: "Anti fungi",
    sizes: ["5L"],
    alt: "Fungiicidal wash image",
  },
  {
    name: "Wrought Iron Matt Black",
    category: "paint-crown",
    type: "specialized",
    description: "Black matt metal paint ",
    sizes: ["1L", "4L"],
    alt: "Wrought iron image",
  },

  {
    name: "Zinc Phosphate Red oxide",
    category: "paint-crown",
    type: "specialized",
    description: "Red metal primer ",
    sizes: ["1L", "4L"],
    alt: "Red oxide image",
  },

  {
    name: "Masonry Primer",
    category: "paint-crown",
    type: "exterior",
    description: "Exterior primer",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown masonry primer image",
  },

  {
    name: "Rust Remover",
    category: "paint-crown",
    type: "specialized",
    description: "Rust remover treatment",
    sizes: ["1L", "5L"],
    alt: "Crown rust remover image",
  },
  {
    name: "Bituminous Paint",
    category: "paint-crown",
    type: "specialized",
    description: "Waterproof black coating",
    sizes: ["1L", "4L"],
    alt: "Crown bituminous paint image",
  },
  {
    name: "Eggshell",
    category: "paint-crown",
    type: "interior",
    description: "Low-sheen interior finish",
    sizes: ["1L", "4L"],
    alt: "Crown eggshell paint image",
  },
  {
    name: "Floor Paint ",
    category: "paint-crown",
    type: "specialized",
    description: "Floor paint",
    sizes: ["1L", "4L"],
    alt: "Crown floor paint image",
  },

  {
    name: "Ruff & Tuff",
    category: "paint-crown",
    type: "exterior",
    description: "Textured exterior coating",
    sizes: ["5kg", "30kg"],
    alt: "Crown ruff and tuff image",
  },
  {
    name: "Transeal",
    category: "paint-crown",
    type: "specialized",
    description: "Semi gloss clear stone sealer",
    sizes: ["1L", "4L"],
    alt: "Transeal image",
  },

  // ===== PAINT - BASCO =====

  {
    name: "Matt Black",
    category: "paint-basco",
    type: "specialized",
    description: " Matt Enamel paint",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco matt black paint image",
  },
  {
    name: "Permagloss",
    category: "paint-basco",
    type: "specialized",
    description: "Gloss enamel",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco permagloss paint image",
  },
  {
    name: "Permaflat White/Soft white",
    category: "paint-basco",
    type: "interior",
    description: "Matt emulsion",
    sizes: ["1/2L", "1L", "5L"],
    alt: "Permaflat image",
  },
  {
    name: "Matt Red Oxide",
    category: "paint-basco",
    type: "specialized",
    description: "Metal primer",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco red oxide primer image",
  },
  {
    name: "Varnish",
    category: "paint-basco",
    type: "wood",
    description: "Clear wood varnish",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco varnish image",
  },
  {
    name: "Silver Aluminium",
    category: "paint-basco",
    type: "specialized",
    description: " Silver Metallic paint",
    sizes: ["1/4L", "1/2L", "1L"],
    alt: "Basco silver aluminium paint image",
  },

  {
    name: "PG Undercoat",
    category: "paint-basco",
    type: "specialized",
    description: "Metal undercoat",
    sizes: ["1/2L", "1L"],
    alt: "Basco undercoat image",
  },
  {
    name: "Standard Thinner",
    category: "paint-basco",
    type: "specialized",
    description: "Paint thinner",
    sizes: ["1L", "5L"],
    alt: "Basco thinner image",
  },
  {
    name: " Duracoat Superfast ",
    category: "paint-basco",
    type: "interior",
    description: "matt emulsion",
    sizes: ["4L", "20L"],
    alt: "Basco waterproofing cream image",
  },
  {
    name: "Turpentine",
    category: "paint-basco",
    type: "specialized",
    description: "Paint solvent",
    sizes: ["1L", "5L"],
    alt: "Basco turpentine image",
  },
  {
    name: "White Spirit",
    category: "paint-basco",
    type: "specialized",
    description: "Paint solvent",
    sizes: ["1L", "5L"],
    alt: "Basco white spirit image",
  },
  {
    name: "Aquagloss Enamel",
    category: "paint-basco",
    type: "specialized",
    description: "Water-based gloss",
    sizes: ["4L"],
    alt: "Basco aquagloss enamel image",
  },
  {
    name: "Aquatech Rainshield",
    category: "paint-basco",
    type: "exterior",
    description: "Exterior waterproofing",
    sizes: ["4L"],
    alt: "Basco rainshield image",
  },
  {
    name: "Floor Paint (Red)",
    category: "paint-basco",
    type: "specialized",
    description: "Floor paint",
    sizes: ["1L"],
    alt: "Basco red floor paint image",
  },

  // ===== PAINT - PLASCON =====
  {
    name: "Budget Emulsion",
    category: "paint-plascon",
    type: "interior",
    description: "Interior matt emulsion",
    sizes: ["4L", "20L"],
    alt: "Plascon budget emulsion image",
  },
  {
    name: "PlascoBinder",
    category: "paint-plascon",
    type: "interior",
    description: "Wall binder",
    sizes: ["4L", "20L"],
    alt: "Plascobinder image",
  },
  {
    name: "Silicone Waterproofing",
    category: "paint-plascon",
    type: "exterior",
    description: "Exterior waterproofing",
    sizes: ["1L", "5L"],
    alt: "Plascon silicone waterproofing image",
  },
  {
    name: "Stucco",
    category: "paint-plascon",
    type: "specialized",
    description: "Ready made wall filler",
    sizes: ["1/2kg", "1kg", "4kg"],
    alt: "Plascon stucco image",
  },
  {
    name: "Woodcare Exterior",
    category: "paint-plascon",
    type: "wood",
    description: "Exterior wood finish",
    sizes: ["1L", "5L"],
    alt: "Plascon woodcare exterior image",
  },

  {
    name: "Anteak Oil",
    category: "paint-plascon",
    type: "wood",
    description: "Teak oil for wood",
    sizes: ["1L", "5L"],
    alt: "Plascon anteak oil image",
  },
  {
    name: "Marine Varnish",
    category: "paint-plascon",
    type: "marine",
    description: "UV-resistant boat varnish",
    sizes: ["1L", "4L"],
    alt: "Plascon marine varnish image",
  },
  {
    name: "Marine Red Lead Primer",
    category: "paint-plascon",
    type: "marine",
    description: "Anti-corrosive marine primer",
    sizes: ["1L", "4L"],
    alt: "Plascon marine primer image",
  },
  {
    name: "Acrylic Sealer Undercoat",
    category: "paint-plascon",
    type: "specialized",
    description: "Acrylic sealer undercoat",
    sizes: ["1L", "4L"],
    alt: "Plascon acrylic sealer image",
  },
  {
    name: "Budget Gloss Undercoat",
    category: "paint-plascon",
    type: "specialized",
    description: "Gloss undercoat",
    sizes: ["4L"],
    alt: "Plascon gloss undercoat image",
  },
  {
    name: "Budget Undercoat",
    category: "paint-plascon",
    type: "specialized",
    description: "Undercoat",
    sizes: ["20L"],
    alt: "Plascon budget undercoat image",
  },

  {
    name: "Wall Cover White",
    category: "paint-plascon",
    type: "exterior",
    description: "Exterior wall coating",
    sizes: ["20L"],
    alt: "Plascon wall cover image",
  },
  {
    name: "Antifouling Black",
    category: "paint-plascon",
    type: "marine",
    description: "Marine hull antifouling paint",
    sizes: ["4L"],
    alt: "Plascon antifouling black image",
  },
  {
    name: "Marine paint",
    category: "paint-plascon",
    type: "marine",
    description: "Marine Topside paint",
    sizes: ["4L"],
    alt: "Marine paint image",
  },
];
