const products = [
  {
    name: "Claw Hammer",
    category: "tools",
    description: "Fiber handle Ingco",
    alt: "Claw hammer image",
  },
  {
    name: "Spade",
    category: "tools",
    description: "Metal Handle",
    alt: "spade metal image",
  },
  {
    name: "Bamburi Cement",
    category: "building",
    description: "50Kg Bag 32.5R Cement",
    alt: " Bamburi Cement Image",
  },
  {
    name: "BRC",
    category: "building",
    description: "A142 X 80MTR",
    alt: "BRC Image",
  },
  {
    name: "PPR Male Adapter",
    category: "plumbing",
    description: "25x1/2 Brass",
    alt: "PPR Male Adapter Image",
  },
  {
    name: "Water Heater",
    category: "plumbing",
    description: "100L Atlantic",
    alt: "Water Heater Image",
  },
  {
    name: "Twin Socket",
    category: "electrical",
    description: "13A Tronic",
    alt: "Twin Socket Image",
  },
  {
    name: "Single Socket",
    category: "electrical",
    description: "13A Tronic",
    alt: "Single Socket Image",
  },
  {
    name: "Covermatt",
    category: "paint",
    description: "Budget Interior Paint",
    alt: "Covermatt Image",
  },
  {
    name: "Luxury",
    category: "paint",
    description: "Premium Interior Paint",
    alt: "Luxury Paint Image",
  },
  {
    name: "Ultraguard Silicone",
    category: "paint",
    description: "Premium Exterior Paint",
    alt: "Ultraguard Paint Image",
  },

  // ===== TOOLS =====
  {
    name: "Screw Driver",
    category: "tools",
    description: "Assorted sizes, flat & Phillips",
    alt: "Screw driver image",
  },
  {
    name: "Measuring Tape",
    category: "tools",
    description: "30m steel tape",
    alt: "Measuring tape image",
  },
  {
    name: "Drill Bit (Makita)",
    category: "tools",
    description: "11mm masonry bit",
    alt: "Drill bit image",
  },
  {
    name: "Drill Machine",
    category: "tools",
    description: "750W corded drill",
    alt: "Drill machine image",
  },
  {
    name: "Angle Grinder",
    category: "tools",
    description: "750W heavy duty",
    alt: "Angle grinder image",
  },
  {
    name: "Sledge Hammer",
    category: "tools",
    description: "3lb with handle",
    alt: "Sledge hammer image",
  },
  {
    name: "Hand Saw",
    category: "tools",
    description: "20 inch wood saw",
    alt: "Hand saw image",
  },
  {
    name: "Spanner (Combination)",
    category: "tools",
    description: "8mm - 24mm sizes available",
    alt: "Combination spanner image",
  },
  {
    name: "Spirit Level",
    category: "tools",
    description: "200cm aluminium",
    alt: "Spirit level image",
  },
  {
    name: "Cutting Disc",
    category: "tools",
    description: "4 inch metal cutting",
    alt: "Cutting disc image",
  },
  {
    name: "Trowel",
    category: "tools",
    description: "6 inch, wooden handle",
    alt: "Trowel image",
  },
  {
    name: "Pipe Wrench",
    category: "tools",
    description: "8 inch heavy duty",
    alt: "Pipe wrench image",
  },
  {
    name: "Claw Hammer",
    category: "tools",
    description: "Small, sturdy handle",
    alt: "Claw hammer image",
  },
  {
    name: "Bench Vice",
    category: "tools",
    description: "4 inch, heavy duty",
    alt: "Bench vice image",
  },
  {
    name: "F-Clamp",
    category: "tools",
    description: "80 x 300mm",
    alt: "F-clamp image",
  },

  // ===== BUILDING MATERIALS =====
  {
    name: "Square Tube",
    category: "building",
    description: "40x40x2mm steel",
    alt: "Square tube image",
  },
  {
    name: "Steel Bar",
    category: "building",
    description: "R6 x 40ft reinforcement bar",
    alt: "Steel bar image",
  },
  {
    name: "Flat Bar",
    category: "building",
    description: "50x6mm steel",
    alt: "Flat bar image",
  },
  {
    name: "Bolt & Nuts",
    category: "building",
    description: "1/4 x 3/4 inch, assorted",
    alt: "Bolt and nuts image",
  },
  {
    name: "Wall Plug",
    category: "building",
    description: "6mm plastic anchor",
    alt: "Wall plug image",
  },
  {
    name: "Manhole Cover",
    category: "building",
    description: "18x18 inch, PVC",
    alt: "Manhole cover image",
  },
  {
    name: "Roofing Sheet",
    category: "building",
    description: "30 gauge box profile, 2-3m",
    alt: "Roofing sheet image",
  },
  {
    name: "Gypsum Screws",
    category: "building",
    description: "3.5 x 40mm",
    alt: "Gypsum screws image",
  },
  {
    name: "DPC (Damp Proof Course)",
    category: "building",
    description: "1m x 7m roll",
    alt: "DPC roll image",
  },
  {
    name: "Grout",
    category: "building",
    description: "3kg tile grout, grey",
    alt: "Tile grout image",
  },
  {
    name: "Weld Mesh",
    category: "building",
    description: "Light gauge",
    alt: "Weld mesh image",
  },
  {
    name: "Chainlink (Coated)",
    category: "building",
    description: "11 gauge, 4-6ft height",
    alt: "Coated chainlink image",
  },
  {
    name: "Chip Board",
    category: "building",
    description: "9mm sheet",
    alt: "Chip board image",
  },
  {
    name: "Rawl Bolt",
    category: "building",
    description: "M6 - M12 sizes",
    alt: "Rawl bolt image",
  },
  {
    name: "Gyproc (Plaster)",
    category: "building",
    description: "25kg bag",
    alt: "Gyproc plaster image",
  },

  // ===== PLUMBING =====
  {
    name: "Shower Mixer",
    category: "plumbing",
    description: "Hot & cold mixer, chrome",
    alt: "Shower mixer image",
  },
  {
    name: "Waste Bend",
    category: "plumbing",
    description: "1.25 inch",
    alt: "Waste bend image",
  },
  {
    name: "Shower Head",
    category: "plumbing",
    description: "8 inch rain shower",
    alt: "Shower head image",
  },
  {
    name: "Basin Mixer",
    category: "plumbing",
    description: "Single lever, chrome",
    alt: "Basin mixer image",
  },
  {
    name: "PPR Male Adapter",
    category: "plumbing",
    description: "32mm - 40mm",
    alt: "PPR male adapter image",
  },
  {
    name: "Sink Mixer",
    category: "plumbing",
    description: "Single lever kitchen mixer",
    alt: "Sink mixer image",
  },
  {
    name: "Pillar Tap",
    category: "plumbing",
    description: "Chrome, single",
    alt: "Pillar tap image",
  },
  {
    name: "PPR Pipe",
    category: "plumbing",
    description: "25mm PN20",
    alt: "PPR pipe image",
  },
  {
    name: "Water Heater",
    category: "plumbing",
    description: "15L Atlantic electric",
    alt: "Water heater image",
  },
  {
    name: "PPR Female Elbow",
    category: "plumbing",
    description: "25mm",
    alt: "PPR female elbow image",
  },
  {
    name: "PVC Tee",
    category: "plumbing",
    description: "3/4 inch",
    alt: "PVC tee image",
  },
  {
    name: "Water Pump",
    category: "plumbing",
    description: "Honda 5HP",
    alt: "Water pump image",
  },
  {
    name: "Kitchen Sink",
    category: "plumbing",
    description: "Double bowl, single drainer",
    alt: "Kitchen sink image",
  },
  {
    name: "Water Tank",
    category: "plumbing",
    description: "1000L",
    alt: "Water tank image",
  },
  {
    name: "Gate Valve",
    category: "plumbing",
    description: "1/2 inch brass",
    alt: "Gate valve image",
  },

  // ===== ELECTRICAL =====
  {
    name: "Flood Light (LED)",
    category: "electrical",
    description: "70W outdoor floodlight",
    alt: "LED flood light image",
  },
  {
    name: "Consumer Unit",
    category: "electrical",
    description: "6-way distribution board",
    alt: "Consumer unit image",
  },
  {
    name: "LED Bulb",
    category: "electrical",
    description: "5W, E27 / B22 fitting",
    alt: "LED bulb image",
  },
  {
    name: "Cable Clip",
    category: "electrical",
    description: "6mm round",
    alt: "Cable clip image",
  },
  {
    name: "Cable Ties (Black)",
    category: "electrical",
    description: "2.5 x 100mm, pack",
    alt: "Black cable ties image",
  },
  {
    name: "Capacitor",
    category: "electrical",
    description: "2uF - 10uF motor capacitor",
    alt: "Capacitor image",
  },
  {
    name: "Tube Light (LED)",
    category: "electrical",
    description: "4ft LED tube",
    alt: "LED tube light image",
  },
  {
    name: "Lamp Holder",
    category: "electrical",
    description: "Straight, ceiling type",
    alt: "Lamp holder image",
  },
  {
    name: "Extension Cord",
    category: "electrical",
    description: "4-way with surge protection",
    alt: "Extension cord image",
  },
  {
    name: "Ceiling Fan",
    category: "electrical",
    description: "Standard household fan",
    alt: "Ceiling fan image",
  },
  {
    name: "Bulkhead Light (LED)",
    category: "electrical",
    description: "Oval, weatherproof",
    alt: "LED bulkhead light image",
  },
  {
    name: "Strip Light",
    category: "electrical",
    description: "10W LED strip",
    alt: "Strip light image",
  },
  {
    name: "Trunking",
    category: "electrical",
    description: "25x16mm cable trunking",
    alt: "Trunking image",
  },
  {
    name: "Switch (Lisse)",
    category: "electrical",
    description: "1-2 gang wall switch",
    alt: "Wall switch image",
  },
  {
    name: "Down Light (LED)",
    category: "electrical",
    description: "6W recessed downlight",
    alt: "LED down light image",
  },

  // ===== SANITARY WARE =====
  {
    name: "Toilet Seat Cover",
    category: "sanitary-ware",
    description: "Standard fit",
    alt: "Toilet seat cover image",
  },
  {
    name: "Hand Wash Basin",
    category: "sanitary-ware",
    description: "14x11 inch corner basin",
    alt: "Hand wash basin image",
  },
  {
    name: "Asian Toilet",
    category: "sanitary-ware",
    description: "Ordinary squat toilet",
    alt: "Asian toilet image",
  },
  {
    name: "Bidet Mixer",
    category: "sanitary-ware",
    description: "Chrome bidet spray mixer",
    alt: "Bidet mixer image",
  },
  {
    name: "Center Waste",
    category: "sanitary-ware",
    description: "1.25 inch basin waste",
    alt: "Center waste image",
  },
  {
    name: "Shower Arm",
    category: "sanitary-ware",
    description: "Short, chrome",
    alt: "Shower arm image",
  },
  {
    name: "Telephone Shower (Flexible)",
    category: "sanitary-ware",
    description: "PVC hose, white",
    alt: "Flexible telephone shower image",
  },
  {
    name: "WC Connector",
    category: "sanitary-ware",
    description: "4 inch, blue",
    alt: "WC connector image",
  },
  {
    name: "Cistern Ball",
    category: "sanitary-ware",
    description: "Float valve for toilet cistern",
    alt: "Cistern ball image",
  },
  {
    name: "Flush Handle (Metal)",
    category: "sanitary-ware",
    description: "Lever type",
    alt: "Metal flush handle image",
  },
  {
    name: "Basin Stopper",
    category: "sanitary-ware",
    description: "Heavy duty",
    alt: "Basin stopper image",
  },
  {
    name: "Soap Dish",
    category: "sanitary-ware",
    description: "Stainless steel",
    alt: "Soap dish image",
  },
  {
    name: "Mirror Light (LED)",
    category: "sanitary-ware",
    description: "4W bathroom mirror light",
    alt: "LED mirror light image",
  },
  {
    name: "Arabic Shower",
    category: "sanitary-ware",
    description: "PVC hand shower",
    alt: "Arabic shower image",
  },
  {
    name: "Toilet Paper Holder",
    category: "sanitary-ware",
    description: "Chrome, wall mount",
    alt: "Toilet paper holder image",
  },

  // ===== HARDWARE GENERAL =====
  {
    name: "Cylinder Lock",
    category: "hardware-general",
    description: "Standard door cylinder",
    alt: "Cylinder lock image",
  },
  {
    name: "Brass Hinges",
    category: "hardware-general",
    description: "3x3 inch, pair",
    alt: "Brass hinges image",
  },
  {
    name: "Drawer Handle",
    category: "hardware-general",
    description: "Small metal pull handle",
    alt: "Drawer handle image",
  },
  {
    name: "Padlock (Triangular)",
    category: "hardware-general",
    description: "40mm, chrome plated",
    alt: "Triangular padlock image",
  },
  {
    name: "Nylon Rope",
    category: "hardware-general",
    description: "8mm, sold per metre",
    alt: "Nylon rope image",
  },
  {
    name: "Mortice Lock",
    category: "hardware-general",
    description: "2-lever door lock",
    alt: "Mortice lock image",
  },
  {
    name: "Hasp & Staple",
    category: "hardware-general",
    description: "4 inch, aluminium",
    alt: "Hasp and staple image",
  },
  {
    name: "Castor Wheel",
    category: "hardware-general",
    description: "1.5 inch swivel wheel",
    alt: "Castor wheel image",
  },
  {
    name: "Garden Shear",
    category: "hardware-general",
    description: "Heavy duty pruning shear",
    alt: "Garden shear image",
  },
  {
    name: "Lawn Mower",
    category: "hardware-general",
    description: "123cc, 16 inch cut",
    alt: "Lawn mower image",
  },
  {
    name: "Screw Hook",
    category: "hardware-general",
    description: "Assorted sizes",
    alt: "Screw hook image",
  },
  {
    name: "Curtain Rod",
    category: "hardware-general",
    description: "7ft, wooden",
    alt: "Curtain rod image",
  },
  {
    name: "Glass Cutter",
    category: "hardware-general",
    description: "Standard hand tool",
    alt: "Glass cutter image",
  },
  {
    name: "Life Jacket",
    category: "hardware-general",
    description: "Orange, adult size",
    alt: "Life jacket image",
  },
  {
    name: "Pool Net",
    category: "hardware-general",
    description: "Deep leaf net for pools",
    alt: "Pool net image",
  },

  // ===== PAINT - BASCO =====
  // ===== PAINT - BASCO =====
  {
    name: "Matt Black",
    category: "paint-basco",
    type: "specialized",
    description: "Enamel paint",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco matt black paint image",
  },
  {
    name: "Permagloss",
    category: "paint-basco",
    type: "specialized",
    description: "Gloss enamel",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco permagloss paint image",
  },
  {
    name: "Permagloss (Tibet Shade)",
    category: "paint-basco",
    type: "specialized",
    description: "Gloss enamel, Tibet shade",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco permagloss tibet shade image",
  },
  {
    name: "PG Red Oxide",
    category: "paint-basco",
    type: "specialized",
    description: "Metal primer",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco red oxide primer image",
  },
  {
    name: "Varnish",
    category: "paint-basco",
    type: "wood",
    description: "Clear wood varnish",
    sizes: ["1/4L", "1/2L", "1L", "4L"],
    alt: "Basco varnish image",
  },
  {
    name: "Silver Aluminium",
    category: "paint-basco",
    type: "specialized",
    description: "Metallic paint",
    sizes: ["1/4L", "1/2L", "1L"],
    alt: "Basco silver aluminium paint image",
  },
  {
    name: "Permaflat White/SW",
    category: "paint-basco",
    type: "interior",
    description: "Matt emulsion",
    sizes: ["20L"],
    alt: "Basco permaflat white paint image",
  },
  {
    name: "PG Undercoat",
    category: "paint-basco",
    type: "specialized",
    description: "Metal undercoat",
    sizes: ["1/2L", "1L"],
    alt: "Basco undercoat image",
  },
  {
    name: "Standard Thinner",
    category: "paint-basco",
    type: "specialized",
    description: "Paint thinner",
    sizes: ["1L", "5L"],
    alt: "Basco thinner image",
  },
  {
    name: "Superfast Waterproofing Cream",
    category: "paint-basco",
    type: "exterior",
    description: "Exterior waterproofing",
    sizes: ["4L", "20L"],
    alt: "Basco waterproofing cream image",
  },
  {
    name: "Turpentine",
    category: "paint-basco",
    type: "specialized",
    description: "Paint solvent",
    sizes: ["1L", "5L"],
    alt: "Basco turpentine image",
  },
  {
    name: "White Spirit",
    category: "paint-basco",
    type: "specialized",
    description: "Paint solvent",
    sizes: ["1L", "5L"],
    alt: "Basco white spirit image",
  },
  {
    name: "Aquagloss Enamel",
    category: "paint-basco",
    type: "specialized",
    description: "Water-based gloss",
    sizes: ["4L"],
    alt: "Basco aquagloss enamel image",
  },
  {
    name: "Aquatech Rainshield",
    category: "paint-basco",
    type: "exterior",
    description: "Exterior waterproofing",
    sizes: ["4L"],
    alt: "Basco rainshield image",
  },
  {
    name: "Floor Paint (Red)",
    category: "paint-basco",
    type: "specialized",
    description: "Floor paint",
    sizes: ["1L"],
    alt: "Basco red floor paint image",
  },

  // ===== PAINT - CROWN =====
  {
    name: "Covermatt",
    category: "paint-crown",
    type: "interior",
    description: "Budget interior matt emulsion",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown covermatt paint image",
  },
  {
    name: "Luxury",
    category: "paint-crown",
    type: "interior",
    description: "Premium interior emulsion",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown luxury paint image",
  },
  {
    name: "Vinyl Silk",
    category: "paint-crown",
    type: "interior",
    description: "Silk finish emulsion",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown vinyl silk paint image",
  },
  {
    name: "Vinyl Matt Extreme",
    category: "paint-crown",
    type: "interior",
    description: "Washable matt emulsion",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown vinyl matt extreme image",
  },
  {
    name: "Permaplast",
    category: "paint-crown",
    type: "exterior",
    description: "Textured exterior finish",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown permaplast image",
  },
  {
    name: "Masonry Primer",
    category: "paint-crown",
    type: "exterior",
    description: "Exterior primer",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown masonry primer image",
  },
  {
    name: "U/G Silicone",
    category: "paint-crown",
    type: "exterior",
    description: "Silicone waterproofing undercoat",
    sizes: ["1L", "4L", "20L"],
    alt: "Crown silicone undercoat image",
  },
  {
    name: "Wood Primer",
    category: "paint-crown",
    type: "wood",
    description: "Wood primer",
    sizes: ["1L", "4L"],
    alt: "Crown wood primer image",
  },
  {
    name: "Rust Remover",
    category: "paint-crown",
    type: "specialized",
    description: "Rust remover treatment",
    sizes: ["1L", "5L"],
    alt: "Crown rust remover image",
  },
  {
    name: "Bituminous Paint",
    category: "paint-crown",
    type: "specialized",
    description: "Waterproof black coating",
    sizes: ["1L", "4L"],
    alt: "Crown bituminous paint image",
  },
  {
    name: "Eggshell",
    category: "paint-crown",
    type: "interior",
    description: "Low-sheen interior finish",
    sizes: ["1L", "4L"],
    alt: "Crown eggshell paint image",
  },
  {
    name: "Floor Paint (All Shades)",
    category: "paint-crown",
    type: "specialized",
    description: "Floor paint",
    sizes: ["1L", "4L"],
    alt: "Crown floor paint image",
  },
  {
    name: "Roof Paint (All Shades)",
    category: "paint-crown",
    type: "exterior",
    description: "Roof paint",
    sizes: ["1L", "4L"],
    alt: "Crown roof paint image",
  },
  {
    name: "Woodseal Clear",
    category: "paint-crown",
    type: "wood",
    description: "Clear wood sealer",
    sizes: ["1L", "4L"],
    alt: "Crown woodseal clear image",
  },
  {
    name: "Ruff & Tuff",
    category: "paint-crown",
    type: "exterior",
    description: "Textured exterior coating",
    sizes: ["5kg", "30kg"],
    alt: "Crown ruff and tuff image",
  },

  // ===== PAINT - PLASCON =====
  {
    name: "Budget Emulsion",
    category: "paint-plascon",
    type: "interior",
    description: "Interior matt emulsion",
    sizes: ["4L", "20L"],
    alt: "Plascon budget emulsion image",
  },
  {
    name: "Vinyl Matt Emulsion",
    category: "paint-plascon",
    type: "interior",
    description: "Washable interior finish",
    sizes: ["4L"],
    alt: "Plascon vinyl matt emulsion image",
  },
  {
    name: "Silicone Waterproofing",
    category: "paint-plascon",
    type: "exterior",
    description: "Exterior waterproofing",
    sizes: ["1L", "5L"],
    alt: "Plascon silicone waterproofing image",
  },
  {
    name: "Stucco",
    category: "paint-plascon",
    type: "exterior",
    description: "Decorative textured finish",
    sizes: ["1/2kg", "1kg"],
    alt: "Plascon stucco image",
  },
  {
    name: "Woodcare Exterior",
    category: "paint-plascon",
    type: "wood",
    description: "Exterior wood finish",
    sizes: ["1L", "5L"],
    alt: "Plascon woodcare exterior image",
  },
  {
    name: "Woodcare Interior",
    category: "paint-plascon",
    type: "wood",
    description: "Interior wood finish",
    sizes: ["1L", "5L"],
    alt: "Plascon woodcare interior image",
  },
  {
    name: "Anteak Oil",
    category: "paint-plascon",
    type: "wood",
    description: "Teak oil for wood",
    sizes: ["1L", "5L"],
    alt: "Plascon anteak oil image",
  },
  {
    name: "Marine Varnish",
    category: "paint-plascon",
    type: "marine",
    description: "UV-resistant boat varnish",
    sizes: ["1L", "4L"],
    alt: "Plascon marine varnish image",
  },
  {
    name: "Marine Red Lead Primer",
    category: "paint-plascon",
    type: "marine",
    description: "Anti-corrosive marine primer",
    sizes: ["1L", "4L"],
    alt: "Plascon marine primer image",
  },
  {
    name: "Acrylic Sealer Undercoat",
    category: "paint-plascon",
    type: "specialized",
    description: "Acrylic sealer undercoat",
    sizes: ["1L", "4L"],
    alt: "Plascon acrylic sealer image",
  },
  {
    name: "Budget Gloss Undercoat",
    category: "paint-plascon",
    type: "specialized",
    description: "Gloss undercoat",
    sizes: ["4L"],
    alt: "Plascon gloss undercoat image",
  },
  {
    name: "Budget Undercoat",
    category: "paint-plascon",
    type: "specialized",
    description: "Undercoat",
    sizes: ["20L"],
    alt: "Plascon budget undercoat image",
  },
  {
    name: "Roof Paint (Green)",
    category: "paint-plascon",
    type: "exterior",
    description: "Roof paint, green",
    sizes: ["4L"],
    alt: "Plascon green roof paint image",
  },
  {
    name: "Wall Cover White",
    category: "paint-plascon",
    type: "exterior",
    description: "Exterior wall coating",
    sizes: ["20L"],
    alt: "Plascon wall cover image",
  },
  {
    name: "Antifouling Black",
    category: "paint-plascon",
    type: "marine",
    description: "Marine hull antifouling paint",
    sizes: ["4L"],
    alt: "Plascon antifouling black image",
  },
];
